export enum ActionType {
  ADD_TODO = 'ADD_TODO',
  DELETE_TODO = 'DELETE_TODO',
  TOGGLE_TODO = 'TOGGLE_TODO',
  EDIT_TODO = 'EDIT_TODO',
  CLEAR_COMPLETED = 'CLEAR_COMPLETED',
  TOGGLE_ALL = 'TOGGLE_ALL',
}
