export enum Actions {
  ADD = 'ADD_TODO',
  DELETE = 'DELETE_TODO',
  UPDATE = 'UPDATE_TODO',
  TOGGLE = 'TOGGLE_TODO',
  TOGGLE_ALL = 'TOGGLE_ALL_TODO',
  CLEAR = 'CLEAR_COMPLETED',
  FILTER = 'SET_FILTER',
}
