export const actions: { [key: string]: string } = {
  INIT_TODOS: 'INIT_TODOS',
  SAVE_TODOS: 'SAVE_TODOS',
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLE_ALL_TODOS: 'TOGGLE_ALL_TODOS',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  SET_FILTER: 'SET_FILTER',
  START_EDITING_TODO: 'START_EDITING_TODO',
  STOP_EDITING_TODO: 'STOP_EDITING_TODO',
  EDIT_TODO: 'EDIT_TODO',
};
