export const CREATE_TODO = 'TODO/CREATE_TODO';

export const DELETE_TODO = 'TODO/DELETE_TODO';

export const COMPLETE_TODO = 'TODO/COMPLETE_TODO';

export const CLEAR_COMPLETED = 'TODO/CLEAR_COMPLETED';

export const TOGGLE_ALL = 'TODOS/TOGLE_ALL';

export const CHANGE_TITLE = 'CHANGE_TITLE';
